"""initial schema

Revision ID: 6d3bb604019d
Revises: 
Create Date: 2026-03-06 20:23:04.194526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3bb604019d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SUBMITTER', 'VIEWER', 'EXTERNAL_CLIENT', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_accession', sa.String(length=20), nullable=False),
    sa.Column('ena_accession', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_type', sa.Enum('WGS', 'METAGENOMICS', 'GENOTYPING', 'TRANSCRIPTOMICS', 'AMPLICON', 'OTHER', name='projecttype'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('license', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_studies_internal_accession'), 'studies', ['internal_accession'], unique=True)
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_accession', sa.String(length=20), nullable=False),
    sa.Column('ena_accession', sa.String(length=20), nullable=True),
    sa.Column('organism', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.Integer(), nullable=False),
    sa.Column('breed', sa.String(length=255), nullable=True),
    sa.Column('collection_date', sa.Date(), nullable=False),
    sa.Column('geographic_location', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('tissue', sa.String(length=255), nullable=True),
    sa.Column('developmental_stage', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=20), nullable=True),
    sa.Column('checklist_id', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_samples_internal_accession'), 'samples', ['internal_accession'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_accession', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'DEPOSITED', 'PUBLISHED', 'FAILED', name='submissionstatus'), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('run_accessions', sa.JSON(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_internal_accession'), 'submissions', ['internal_accession'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_accession', sa.String(length=20), nullable=False),
    sa.Column('ena_accession', sa.String(length=20), nullable=True),
    sa.Column('platform', sa.Enum('ILLUMINA', 'OXFORD_NANOPORE', 'PACBIO_SMRT', 'SNP_CHIP', 'HI_C', name='platform'), nullable=False),
    sa.Column('instrument_model', sa.String(length=255), nullable=False),
    sa.Column('library_strategy', sa.Enum('WGS', 'WXS', 'RNA_SEQ', 'AMPLICON', 'TARGETED', 'OTHER', name='librarystrategy'), nullable=False),
    sa.Column('library_source', sa.Enum('GENOMIC', 'TRANSCRIPTOMIC', 'METAGENOMIC', 'OTHER', name='librarysource'), nullable=False),
    sa.Column('library_layout', sa.Enum('PAIRED', 'SINGLE', name='librarylayout'), nullable=False),
    sa.Column('insert_size', sa.Integer(), nullable=True),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_internal_accession'), 'experiments', ['internal_accession'], unique=True)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_accession', sa.String(length=20), nullable=False),
    sa.Column('ena_accession', sa.String(length=20), nullable=True),
    sa.Column('file_type', sa.Enum('FASTQ', 'BAM', 'CRAM', 'VCF', 'IDAT', 'BED_BIM_FAM', 'PED_MAP', 'CSV', 'OTHER', name='filetype'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum_md5', sa.String(length=32), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_internal_accession'), 'runs', ['internal_accession'], unique=True)
    op.create_table('qc_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASS', 'WARN', 'FAIL', name='qcstatus'), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('report_path', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qc_reports')
    op.drop_index(op.f('ix_runs_internal_accession'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_experiments_internal_accession'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_submissions_internal_accession'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_samples_internal_accession'), table_name='samples')
    op.drop_table('samples')
    op.drop_index(op.f('ix_studies_internal_accession'), table_name='studies')
    op.drop_table('studies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
